### ISSUE TITLE
punchlist for release

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#15]
- [x] change title from 'AI Model Tester' to "AI Tester" it's shorter which is generally better, also we are not just testing 'models' as some will be systems like rekognition, etc.
- [x] add 'Upload videos' above 'select videos' with upload button on that row
- [x] run model / inference with upload (since users would most commonly expect that)
- [x] change 'select files' to 'select videos'
- [x] alphabetical order for models
- [x] make clear which models are faces
- [x] add in greg help text modified for technical accuracy
- [x] beefier EC2 instance
- [x] allow uploading multiple videos
- [x] look for aws alternative to always on gpu
- [x] for IPVM library, change to "IPVM Sample Videos" and clean up the file names
- [x] also right now the samples are all 1 lux, 0 down, let's have some variety 200 lux, 30 down, etc.
- [x] in the output list, show the resolution of the video, this is helpful as it can point to problems, i.e., the resolution might be too low or the fov too wide for that resolution

others for future:
- [ ] google and microsoft cloud add to list of models / options
- [ ] add rekognition for objects

**Comment by john-honovich** [comment]
the most important overall but not listed above is updating the progress bar regularly, if a user does not see change for more than 5 seconds they will most likely thing the service is broken, 

it taking 3 minutes is not great but it's much better as long as the progress bar updates even 0.1% every second or so

e.g. i am uploading a clip now and for more than 20 seconds this progress text has been static so i have no idea if it's broken overall or just progress update is not clear
<img width="427" alt="screen shot 2019-02-05 at 4 03 48 pm" src="https://user-images.githubusercontent.com/8518367/52307264-bbbf0200-295f-11e9-90ae-f827363796f9.png">

**Comment by john-honovich** [comment]
any progress on the uploding / progress bar? 2 minutes ago i submitted a 3 second clip and its showing "Preprocessing video (rotating, clipping)..."

we can't ship without fixing this, i see the multiple files upload is being worked on but until progress shows correctly, multiple file uploads will only make this problem much worse

**Comment by john-honovich** [comment]
10 minutes later, that 2 second clip is still hung at "Preprocessing video (rotating, clipping)..."

**Comment by john-honovich** [comment]
i like that we show the file's name but i think we should hide the auto generated ID that is appended for display purposes, as it takes up space and the user does not need to know it
e.g.
![image](https://user-images.githubusercontent.com/8518367/52493355-dc21d300-2b90-11e9-96eb-3d5c0253aa06.png)

**Comment by john-honovich** [comment]
beefier EC2 instance for processing

**Comment by john-honovich** [comment]
I've updated the punchlist to what we discussed and a few others, new items copied below:

- change title from 'AI Model Tester' to "AI Tester" it's shorter which is generally better, also we are not just testing 'models' as some will be systems like rekognition, etc.
- add 'Upload videos' above 'select videos' with upload button on that row 
- run model / inference with upload (since users would most commonly expect that)
- change 'select files' to 'select videos'
- beefier EC2 instance
- for IPVM library, change to "IPVM Sample Videos" and clean up the file names
- also right now the samples are all 1 lux, 0 down, let's have some variety 200 lux, 30 down, etc.
- in the output list, show the resolution of the video, this is helpful as it can point to problems, i.e., the resolution might be too low or the fov too wide for that resolution

**Comment by lefnire** [comment]
checked off easy ones, switching to harder ones

**Comment by john-honovich** [comment]
Looking good!

Small text change here
“Curious about all the different "models" (AI systems) for detecting faces
on your videos? We're here to help! Upload a video and we'll analyze the
first 10 seconds to show you how each model performs, and what
faces/objecsts it detects.”

Change the first reference from faces to Objects and correct spelling of
objects at end

**Comment by john-honovich** [comment]
Looking good!
Only thing, as discussed, I see is to cut the list of samples down. I actually think it will be easier especially at first since a long list may be more overwhelming.

Any barriers you see to sharing the beta (limited) tomorrow?
i am curious about #19 if its easy to add a frame by frame control but that's minor

**Comment by lefnire** [comment]
@john-honovich 
>  also right now the samples are all 1 lux, 0 down, let's have some variety 200 lux, 30 down, etc.

You wanted ~5. If I picked min/max (2) of all options, we got 4^2=16 (that's the original library; excluding recent snow/color/etc stuff). Want me to do min/max & get more than originally planned, or you wanna maybe grab-bag a few & LMK?

Got the others done. My own added items:
- [ ] cache job-runs `key=[file.id, job.device, job.model]`
- [ ] get `systemd` script working so server / job-server restarts on reboot. Then create EC2 spot-instance for GPU to save $$

**Comment by john-honovich** [comment]
how about? 
indoor 1 lux
indoor 200 lux
1 snow
1 color 
1 IR

doesn't need to be exact just each one should be clearly visually different than the others (either different scene or different lighting or different weather, etc.)

**Comment by lefnire** [comment]
Kk, I selected some of those; LMK if prefer others (I did one snow mono/color, so +1). Misc other fixes. Temp fix on 10s clips: I clip to "15s" (since it +-5s, hopefully floor is 10s). I'll do real fix later (a tad involved).

**Comment by john-honovich** [comment]
that's good!
for the naming, let's put the scene first so "0down-0side-headup-9lux-snow-color" would be "snow-color-0down-0side-headup-9lux", it will be a little easier to read / scan

the clip is fine, i just don't want it to be shorter than what we say (e.g., 15s clip when we say 10s is fine but a 5s clip when we say 10s may cause people to feel 'cheated')

**Comment by lefnire** [comment]
>for the naming, let's put the scene first so "0down-0side-headup-9lux-snow-color" would be "snow-color-0down-0side-headup-9lux", it will be a little easier to read / scan

√

**Comment by john-honovich** [comment]
change "Curious about all the different models (AI systems) for detecting objects on your videos?"
to "Curious how different AI models will work on your videos?" 
i think that is clearer and is also shorter

and remove "and what faces/objects it detects." at the end since it does not add much more information

**Comment by john-honovich** [comment]
for the naming, for ones that do not have a scene name, add it e.g. "200lux-28down-30side-headup" becomes "Indoor-200lux-28down-30side-headup"

**Comment by lefnire** [comment]
√ √

**Comment by john-honovich** [comment]
- for users not logged in, let them run the sample models, the only part that needs to be logged in for is uploading videos (move the login text up to that and hyperlink it to /login)
Note: that is not necessary for the beta announcement tomorrow since we are focusing on members but useful to have that done
- to do tonight or tomorrow, just add the word '(BETA)' after the title "AI Tester" so it should display "AI Tester (BETA)" to clarify status of the app

**Comment by lefnire** [comment]
√ √

**Comment by john-honovich** [comment]
the non logged in user option looks very nice!
<img width="485" alt="screen shot 2019-02-12 at 8 32 15 pm" src="https://user-images.githubusercontent.com/8518367/52682583-9b65e900-2f05-11e9-833c-c39a954e81a0.png">

closing this out!
