### ISSUE TITLE
what video file / formats do we support?

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#17]
do we have a known list of video file formats supported?
MP4, AVI, MOV, FLV, WMV, etc.

we don't need to support 'all' or even most video file formats
we do need to give clarity on what formats are officially supported as well as clear error message if someone uploads something not supported

**Comment by lefnire** [comment]
currently .mp4,.mov,.avi. Maybe have been a bug I just fixed, try again. I added helper text under the input indicating accepted filetypes. It _should_ be able to accept all video types, I'll try expanding the list today & ensuring no problems

**Comment by john-honovich** [comment]
good with that text
what happens if someone uploads a .wmv for example? what error or response would the app give?

i am fine with just allowing ".mp4,.mov,.avi" and if someone uploads anything else the system immediately rejects it, thoughts?

**Comment by lefnire** [comment]
already it just restricts the selectable files

**Comment by lefnire** [comment]
The server does respond with an error if they get around that `<input accepts=... />` somehow.

**Comment by john-honovich** [comment]
ok good!
