### ISSUE TITLE
is 10s limit being held?

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#18]
i uploaded a 14 second clip and all 14 seconds was processed
here is the output 14 second clip https://s3.amazonaws.com/ai-models-staging/vids/out/yolov3-0.951acc-GPU-IMG_6509-PJV-Dy7OTcOC9DF9_P2Arg.mp4

so are we not capping at 10s or?

**Comment by john-honovich** [comment]
does not seem to be limiting, here is 28s or so video output https://s3.amazonaws.com/ai-models-staging/vids/out/yolov3-1.0acc-GPU-trimmed-us-senator-hikua_1-U9wuF909Q9aDsrTeX0ndLQ.mp4

**Comment by lefnire** [comment]
Updated, try now

**Comment by lefnire** [comment]
It currently clips to an estimate around 10s (not exactly 10s) due to some frame calculations in OpenCV. If we want exactly 10s, I'll do some digging

**Comment by john-honovich** [comment]
does not need to be exact thanks

**Comment by john-honovich** [comment]
looks like videos are being cropped to 5s or 6s, please check
it does not need to be exactly 10 but it should be in 9 to 11 range
