### ISSUE TITLE
CRUD for selecting videos

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#21]
add edit name of videos uploaded and delete option (with confirmation)
![image](https://user-images.githubusercontent.com/8518367/52654148-03d9a980-2eb7-11e9-9e9c-9d52e78b5796.png)

not sure the best UX for this, can be kept simple first

**Comment by lefnire** [comment]
Added a delete button, started working on edit button but it's a bit more involved; more tomorrow

**Comment by john-honovich** [comment]
ok delete works well
i think we should put the delete button on the right hand side (seems more conventional) and make a bit smaller, also perhaps only show after a row is selected so it's less visible (since a user wanting to delete will naturally click on the row first)

**Comment by lefnire** [comment]
how about that?

**Comment by john-honovich** [comment]
that looks nice!
all set on deleting

**Comment by lefnire** [comment]
[√] CRUD: edit

**Comment by john-honovich** [comment]
Looks good, this is done!
