### ISSUE TITLE
multi model selection

### ISSUE THREAD

**Issue by lefnire** [ipvideomarketinfo/ai-model-tester#29]
@john-honovich I just realized we'll need to add device-selection per-model in the multi model situation. See https://staging.ai.ipvm.com for my take on it. Don't submit, won't work - I'll modify server routes accordingly if you like this look.

Or do we prefer to go whole-hog and they can multi-select everything?
```
---
select videos
[ ] 1
[ ] 2
[ ] 3
---
select models
[ ] yolo
[ ] cnn
---
select devices
[ ] cpu
[ ] gpu
[ ] myriad x
```

**Comment by john-honovich** [comment]
so that would eliminate the device selection and put it in line with the model? if so I like that as it shortens the input and puts device selection right next to the model which makes more physical sense

**Comment by lefnire** [comment]
√
