### ISSUE TITLE
change 'running model' to 'running' specific model name

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#30]
when a model is running we display:
<img width="325" alt="screen shot 2019-02-15 at 8 55 06 pm" src="https://user-images.githubusercontent.com/8518367/52893643-0d3b6e00-3164-11e9-9d67-f6a05f99537f.png">

now that we let people run multiple models on the same video, it would be clearer to say the specific model name rather than just 'model'

**Comment by lefnire** [comment]
give that a gander

**Comment by john-honovich** [comment]
very nice!
<img width="564" alt="screen shot 2019-02-16 at 7 29 00 am" src="https://user-images.githubusercontent.com/8518367/52900532-8ebeea80-31bc-11e9-8b3c-df0c5fbb4a55.png">
