### ISSUE TITLE
error when trying to run 5 models at once on a single video

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#31]
this was my input:
<img width="1034" alt="screen shot 2019-02-15 at 8 56 30 pm" src="https://user-images.githubusercontent.com/8518367/52893653-3c51df80-3164-11e9-9345-56525e16d42a.png">

2 of the 5 failed
error message copied below, i think they are the same but was shown in 2 different places
<img width="1040" alt="screen shot 2019-02-15 at 8 57 14 pm" src="https://user-images.githubusercontent.com/8518367/52893666-918df100-3164-11e9-8445-29d1891c075b.png">

<img width="1015" alt="screen shot 2019-02-15 at 8 57 22 pm" src="https://user-images.githubusercontent.com/8518367/52893661-58ee1780-3164-11e9-97ee-04c3ba4075b6.png">

please check and fix thanks

**Comment by lefnire** [comment]
should be fixed now

**Comment by john-honovich** [comment]
good
