### ISSUE TITLE
is yolov3 objects being selected by default

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#32]
i went to incognito mode and yolov3 is selected by default with me selecting anything
am i confused or?
see below:
<img width="1022" alt="screen shot 2019-02-16 at 7 30 19 am" src="https://user-images.githubusercontent.com/8518367/52900549-d5ace000-31bc-11e9-9d3c-222c52c2bcee.png">

no model should be selected by default yes? the user might be confused of why it was generated

**Comment by lefnire** [comment]
Vestige from before, i'll fix
