### ISSUE TITLE
output videos too big?

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#33]
i think this is partially fixing an edge case, partially thinking about how large videos should be

with this portrait aspect ratio video it's clearly way too big, it's 352 x 640 but it's being displayed gigantically
<img width="1073" alt="screen shot 2019-02-16 at 7 34 20 am" src="https://user-images.githubusercontent.com/8518367/52900604-929f3c80-31bd-11e9-929b-5d420116a157.png">

let's shrink that

secondly on conventional HD aspect ratio 1920 x 1080, they fit better, see example below:
<img width="974" alt="screen shot 2019-02-16 at 7 37 26 am" src="https://user-images.githubusercontent.com/8518367/52900618-bfebea80-31bd-11e9-928f-35493ae8dd4f.png">

are videos being set to 100% width horizontally?
maybe 75%, not sure, but the bigger the videos are the harder it is to scroll, see all information
also the boxes should be pretty easy to see even smaller 
related, can we enable the full screen option which seems to be disabled right now? e.g.
![image](https://user-images.githubusercontent.com/8518367/52900657-10634800-31be-11e9-87a8-a5703980c008.png)

**Comment by john-honovich** [comment]
@lefnire any thoughts here?

**Comment by lefnire** [comment]
@john-honovich the expand button's enabled for me, I'll investigate what causes disable.

can you send me the small video?

It is indeed set `width: 100%`. I can set `max-width: 100%` or some pixel value, or `max-width: 75%` or such. I'll play around with options

**Comment by john-honovich** [comment]
here is the small video https://ipvm-uploads.s3.amazonaws.com/uploads/947a/c84d/Sunell%20Body%20Temp%20Demo.mp4

**Comment by lefnire** [comment]
Trying `max-width: 75%`, give that a gander (do you prefer left-justified or center?)

**Comment by john-honovich** [comment]
left justified since it will then line up with the description below
<img width="1019" alt="screen shot 2019-02-18 at 3 39 09 pm" src="https://user-images.githubusercontent.com/8518367/52977587-61786500-3393-11e9-8749-dd9bb9c65c0c.png">

and the moderately smaller size looks better
oh and the full screen button is enabled for me now

**Comment by lefnire** [comment]
I left-justified, and sounds like the others are fixed. Re-open if still issues

**Comment by john-honovich** [comment]
thanks!
