### ISSUE TITLE
one long scroll

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#34]
looks like there is no one long scroll for AI tester that covers all the inputs and output videos, this can be confusing because users expect to scroll the page, here is an example gif:
![one-scroll-example](https://user-images.githubusercontent.com/8518367/52901086-03495780-31c4-11e9-8290-ab534372e9ef.gif)

i think there should be scrolls for just the individual inputs as you had originally, scroll for (1) select videos and (2) for select models

does that make sense?

**Comment by lefnire** [comment]
The inputs should have scrolls currently, 500px max-height (I can shorten that if desired). 

The long input is a thing with the embedded iframe; issues w/ handing dynamic iframe height w/i a parent page. One for @nshoes I think, we were wondering how this would play out - Nate any ideas?

**Comment by john-honovich** [comment]
well this is my macbook air with a 2560 x 1600 display at 100%, notice how i can only see the select videos portion and nothing lower 
<img width="1440" alt="screen shot 2019-02-16 at 11 17 28 am" src="https://user-images.githubusercontent.com/8518367/52902870-95f5f080-31dc-11e9-8df6-53f36619de24.png">

is there something wrong or particular to my screen?

more generally each input is showing 10 rows, i think we can reduce that to 5 rows or whatever the pixel equivalent of that is, thoughts?

**Comment by john-honovich** [comment]
circling back if we reduce each input to ~5 rows, i think that's a good balance between seeing options and not having to scroll down so long to see output videos, etc.

**Comment by lefnire** [comment]
How about now, `max-height: 250px`? I'm including 5.5 rows (.5 so they see there's cut-off & know to scroll) but also including the headers, LMK if prefer different. 

Again for the big scrollbar, that one's in @nshoes park re: iframe height.  Dunno if fixable, I'll ping him via Slack (I don't think he gets notifs on this repo)

**Comment by john-honovich** [comment]
i think 200 is fine, you still see a lot of each section

one thing we need is some form of separator between the 2 inputs, it kind of blends in between the two which can be confusing
<img width="1236" alt="screen shot 2019-02-18 at 4 09 27 pm" src="https://user-images.githubusercontent.com/8518367/52978631-bc13c000-3397-11e9-884e-e3eba8e7f804.png">

**Comment by lefnire** [comment]
@john-honovich how's that?

**Comment by john-honovich** [comment]
great, the borders really help!
