### ISSUE TITLE
change text for face listing

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#35]
for consistency, change 'Azure Face' to 'Microsoft Azure' and for 'Google Vision Faces' drop the 'Faces' at the end
<img width="348" alt="screen shot 2019-02-19 at 6 58 16 am" src="https://user-images.githubusercontent.com/8518367/53016767-fc188880-3413-11e9-9816-5f1f400c2953.png">

**Comment by lefnire** [comment]
√
