### ISSUE TITLE
YOLO 'waiting for device'

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#39]
YOLO and tiny YOLO both 'waiting for device'
but amazon rekognition and google vision works

please check

waiting for device screencap:
<img width="831" alt="screen shot 2019-02-26 at 8 32 36 am" src="https://user-images.githubusercontent.com/8518367/53420389-54660200-39a1-11e9-93b6-64957263895d.png">

**Comment by lefnire** [comment]
just fixed now, the job queue was catching my library-uploads and hogging all the resources. Fixed so my lib uploads are all done on my computer and restarted services.

Refresh or cancel jobs, try again

**Comment by john-honovich** [comment]
"Fixed so my lib uploads are all done on my computer and restarted services."
Thanks! To clarify, what does 'lib uploads' refer to here?

**Comment by lefnire** [comment]
I'm running the full video-library (old & new Rob videos) through yolov3, collecting the attributes on them (lux, snow, color/mono) etc. I'm doing this to find the attrs that most effect accuracy so I can dive into manually assessing.

I'm running these one-by-one on my home computer, but the EC2 job servers were grabbing those jobs before my computer had a chance. I fixed that

**Comment by lefnire** [comment]
I'm running the full video-library (old & new Rob videos) through yolov3, collecting the attributes on them (lux, snow, color/mono) etc. I'm doing this to find the attrs that most effect accuracy so I can dive into manually assessing.

I'm running these one-by-one on my home computer, but the EC2 job servers were grabbing those jobs before my computer had a chance. I fixed that

**Comment by john-honovich** [comment]
got it, makes sense thanks, closed
