### ISSUE TITLE
upload / sample videos missing

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#40]
not sure what happened or it's just my computer see mising below videos pane
<img width="991" alt="screen shot 2019-02-26 at 9 11 07 am" src="https://user-images.githubusercontent.com/8518367/53423187-8463d400-39a6-11e9-9e76-4f83c16a1bfa.png">

**Comment by lefnire** [comment]
boarding now, will do my best to keep up between now & tonight

**Comment by john-honovich** [comment]
works now! i'll close
