### ISSUE TITLE
YOLO object labeling

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#9]
our other models, so far, I believe are face only, i.e., anything with a bounding box is a face

but with YOLO objects, there are many object categories detected
with yolo objects now working i ran my first clip through and the output detects a person and 2 bottles but the bounding boxes are unlabelled
e.g.
<img width="1175" alt="screen shot 2019-01-15 at 10 09 02 am" src="https://user-images.githubusercontent.com/8518367/51154485-dcd78a00-18ae-11e9-8df7-81b1f55cf007.png">
output clip https://ipvm-uploads.s3.amazonaws.com/uploads/ea08/011e/yolov3-0.0acc-760b680b-c1ce-4815-8de9-840dc025c6cd.be4e5563-7ee1-40ab-94a0-4a259a4fb47e-GPU.mp4

can we label bounding boxes? i am assuming we get that metadata?

**Comment by lefnire** [comment]
https://github.com/ipvideomarketinfo/ai-model-tester/commit/22afe2e8cc1ccd8cb7c096e10136d997cbd80383
